services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    hostname: docmost
    # depends_on:
    # - docmost_db
    # - docmost_redis
    environment:
      APP_URL: http://docmost.${DOMAIN}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - 3005:3000
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/docmost/app:/app/data/storage
    networks:
      - backend
      - frontend
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      traefik.docker.network: backend
      traefik.http.routers.docmost.entrypoints: homesec
      traefik.http.routers.docmost.rule: Host(`docmost.${DOMAIN}`)
networks:
  backend:
    external: true
  frontend:
    external: true
