services:
  calibre-web-automated:
    container_name: calibre-web-automated
    hostname: calibre-web-automated
    image: crocodilestick/calibre-web-automated:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Berlin
    volumes:
      - /mnt/cache/appdata/calibre-web-automated/calibre/config:/config
      - /mnt/cache/appdata/calibre-web-automated/calibre/book:/cwa-book-ingest
      - /mnt/cache/appdata/calibre-web-automated/calibre/library:/calibre-library
    ports:
      - 8083:8083
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=backend
      - traefik.http.routers.cwa.entrypoints=homesec
      - traefik.http.routers.cwa.rule=Host(`cwa.${DOMAIN}`)
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:8383]/system/status
      - net.unraid.docker.icon=https://raw.githubusercontent.com/JPDVM2014/icons/35eb799864f41502e741075abfc6457ba0edefd6/calibre-web-logo.png
      - net.unraid.docker.shell=bash
networks:
  frontend:
    external: true
