services:
  postgres:
    security_opt:
      - no-new-privileges:true
    image: postgres:17
    container_name: postgresql17
    hostname: postgresql17
    ports:
      - 5432:5432/tcp
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /mnt/cache/appdata/postgresql17:/var/lib/postgresql/data:rw
    networks:
      - backend
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/sgraaf/Unraid-Docker-Templates/main/postgresql17/icon.png
      - net.unraid.docker.shell=bash
networks:
  backend:
    external: true
