services:
  signal:
    container_name: signal
    hostname: signal
    image: bbernhard/signal-cli-rest-api:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - MODE=normal
      - SIGNAL_CLI_UID=99
      - SIGNAL_CLI_GID=100
      - AUTO_RECEIVE_SCHEDULE=0 22 * * *
    ports:
      - 8080:8080
    volumes:
      - ./signal-api:/home/.local/share/signal-cli
    networks:
      - backend
    labels:

      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/signalapp/Signal-Desktop/refs/heads/main/images/signal-logo-desktop-linux.png
      - net.unraid.docker.shell=bash
networks:
  backend:
    external: true
