# Globale Einstellungen
global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

# Log & Accesslog
log:
  level: INFO
  # filePath: /var/log/traefik/traefik.log

accessLog:
  # filePath: /var/log/traefik/access.log
  format: json
  bufferingSize: 0
  filters:
    statusCodes:
      - "200-299"
      - "400-599"
    retryAttempts: true
    minDuration: 10ms
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

# API & Dashboard
api:
  dashboard: true
  insecure: false

# Entrypoints
entryPoints:
  # External
  web:
    address: ":81"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":444"
    http3:
      advertisedPort: 444
    http:
      middlewares:
        - "sec-chain@file"
      tls:
        certResolver: letsencrypt
        domains:
          - main: "yourdomain.com"
            sans:
              - "*.yourdomain.com"
  # Internal
  home:
    address: ":80"
    observability:
      accessLogs: false
    http:
      redirections:
        entryPoint:
          to: homesec
          scheme: https
          permanent: true
  homesec:
    address: ":443"
    observability:
      accessLogs: false
    http3:
      advertisedPort: 443
    http:
      middlewares:
        - "basic-chain@file"
      tls:
        certResolver: letsencrypt
        domains:
          - main: "yourdomain.com"
            sans:
              - "*.yourdomain.com"

# Provider (Docker & File)
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "frontend"
    defaultRule: "Host(`{{ .Name }}.{{ index .Labels \"customLabel\"}}`)"
  file:
    directory: /etc/traefik/conf
    watch: true

# Certificate Resolver (LetsEncrypt via cloudflare)
certificatesResolvers:
  letsencrypt:
    acme:
      email: "user@example.com"
      storage: /etc/traefik/certs/acme.json
      certificatesDuration: 2160 # 90 Tage
      keyType: EC384
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        propagation:
          delayBeforeChecks: 20

# Plugins
experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.5
    coraza-http-wasm-traefik:
      moduleName: "github.com/jcchavezs/coraza-http-wasm-traefik"
      version: "v0.3.0"
