services:
  komga:
    container_name: komga
    hostname: komga
    image: gotson/komga
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 25600:25600/tcp
    volumes:
      - /mnt/user/Daten/Ebooks/:/books:rw
      - ./komga:/config:rw
    environment:
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=#recycle,@eaDir
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:25600]
      - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/komga.png
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.komga.entrypoints=websecure,homesec
      - traefik.http.routers.komga.rule=Host(`eb2.${DOMAIN}`)
    networks:
      - frontend
networks:
  frontend:
    external: true
