services:
  komga:
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:25600]
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/komga.png