services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    pull_policy: always
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    user: 1000:1000
    ports:
      - 9090:9090/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${APPDATA_PATH}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${APPDATA_PATH}/prometheus/config/rules:/etc/prometheus/rules:ro
      - ${APPDATA_PATH}/prometheus/data/:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.enable-lifecycle
      - --web.enable-admin-api
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:9090]
      - net.unraid.docker.shell=bash
    environment:
      - TZ=${TZ}
    networks:
      - backend
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.cpu.info
    pid: host
    volumes:
      - /:/host:ro,rslave
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.shell=bash
    environment:
      - TZ=${TZ}
  # dcgm-exporter:
  #   image: nvidia/dcgm-exporter:4.3.1-4.4.1-ubuntu22.04
  #   container_name: dcgm-exporter
  #   pull_policy: always
  #   restart: unless-stopped
  #   gpus: all
  #   cap_add:
  #     - SYS_ADMIN
  #   security_opt:
  #     - no-new-privileges:true
  # labels:
  #     - net.unraid.docker.managed=composeman
  #     - net.unraid.docker.shell=bash#   
  # environment:
  #     - TZ=${TZ}
  #   networks:
  #     - backend
  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:latest
    container_name: smartctl-exporter
    pull_policy: always
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      - backend
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.shell=bash
    environment:
      - TZ=${TZ}
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - prometheus
    user: 99:100
    ports:
      - 3004:3000/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${APPDATA_PATH}/grafana/data:/var/lib/grafana
      - ${APPDATA_PATH}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${APPDATA_PATH}/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:3004]
      - net.unraid.docker.shell=bash
    environment:
      - TZ=${TZ}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    networks:
      - backend
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.shell=bash
    environment:
      - TZ=${TZ}
    networks:
      - backend
networks:
  backend:
    external: true
