services:
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 7318:8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberchef.entrypoints=homesec
      - traefik.http.routers.cyberchef.rule=Host(`cyberchef.${DOMAIN}`)
      - traefik.http.services.cyberchef.loadbalancer.server.port=8000
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.shell=sh
    networks:
      - frontend
networks:
  frontend:
    external: true
