services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      - internal
      - frontend
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - ${EXT_LOCATION}:/libraries
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - valkey
      - immich_postgres
    restart: always
    healthcheck:
      disable: false
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.immich.entrypoints=websecure,homesec
      - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:2283]/files/
      - net.unraid.docker.icon=https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png
      - net.unraid.docker.shell=bash
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - internal
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./immich/model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://github.com/friendlyFriend4000/ImmichStat/blob/main/immichlogotemp.png?raw=1
      - net.unraid.docker.shell=bash
  valkey:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    networks:
      - internal
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/SnuK87/unraid-templates/refs/heads/main/icons/valkey-logo.png
      - net.unraid.docker.shell=bash
  immich_postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://github.com/SpaceinvaderOne/Docker-Templates-Unraid/blob/master/spaceinvaderone/docker_icons/postgresql-immich-logo.png?raw=true
      - net.unraid.docker.shell=bash
networks:
  internal:
    internal: true
  frontend:
    external: true
