services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.19
    container_name: zerobyte
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN
    ports:
      - 4096:4096
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zerobyte:/var/lib/zerobyte
      - /mnt/user:/mnt/user:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.zerobyte.entrypoints=homesec
      - traefik.http.routers.zerobyte.rule=Host(`zerobyte.${DOMAIN}`)
      - traefik.http.services.zerobyte.loadbalancer.server.port=4096
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:4096]
      - net.unraid.docker.icon=https://raw.githubusercontent.com/nicotsx/zerobyte/refs/heads/main/public/images/favicon/web-app-manifest-192x192.png
      - net.unraid.docker.shell=sh
    networks:
      - frontend
networks:
  frontend:
    external: true
