localCustomFormatsPath: /app/cfs
localConfigTemplatesPath: /app/templates

whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

radarr:
  radarr-main:
    base_url: !secret radarr_url
    api_key: !secret radarr_apikey
    include:
      - template: template-radarr-naming
      - template: template-radarr-german
      - template: 425da1ba30711b55d2eb371437ec98d7 # https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
      - template: 2b90e905c99490edc7c7a5787443748b # https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-hd-bluray-web.json
        source: TRASH
    renameQualityProfiles:
      - from: "[German] UHD Bluray + WEB (Alternative)"
        to: Any
      - from: "[German] HD Bluray + WEB"
        to: kids

  radarr-kids:
    base_url: !secret radarr_kids_url
    api_key: !secret radarr_kids_apikey
    quality_definition:
      type: anime # Quality definition type for Radarr
    include:
      - template: template-radarr-naming
      - template: template-radarr-kids-german
      - template: 2b90e905c99490edc7c7a5787443748b # https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/quality-profiles/german-hd-bluray-web.json
        source: TRASH
    renameQualityProfiles:
      - from: "[German] HD Bluray + WEB"
        to: Any

sonarr:
  sonarr:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey
    include:
      - template: template-sonarr-naming
      - template: template-sonarr-german
      - template: 7324309a7d1e10dc0dc2cea6c70ed852 # https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
    renameQualityProfiles:
      - from: "[German] UHD Bluray + WEB (Alternative)"
        to: Any

  sonarr_as:
    base_url: !secret sonarr_as_url
    api_key: !secret sonarr_as_apikey
    include:
      - template: template-sonarr-naming
      - template: template-sonarr-anime-german
      - template: 7324309a7d1e10dc0dc2cea6c70ed852 # https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/quality-profiles/german-uhd-bluray-web-alternative.json
        source: TRASH
    renameQualityProfiles:
      - from: "[German] UHD Bluray + WEB (Alternative)"
        to: Any
