radarr_url: http://radarr:7878
radarr_apikey:
radarr_kids_url: http://radarr_kids:7878
radarr_kids_apikey:
sonarr_url: http://sonarr:8989
sonarr_apikey:
sonarr_as_url: http://sonarr_as:8989
sonarr_as_apikey:
