services:
  spotizerr:
    image: spotizerrphoenix/spotizerr
    user: 99:100
    volumes:
      - ./spotizerr/data:/app/data
      - /mnt/user/Downloads/spotizerr:/app/downloads
      - ./spotizerr/logs:/app/logs
      # - ./spotizerr/.cache:/app/.cache
    ports:
      - 7171:7171
    container_name: spotizerr-app
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.spotizerr.entrypoints=homesec
      - traefik.http.routers.spotizerr.rule=Host(`spotizerr.${DOMAIN}`)
      - traefik.http.services.spotizerr.loadbalancer.server.port=7171
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.shell=bash
    env_file:
      - .env
    networks:
      - frontend
networks:
  frontend:
    external: true
