# HEY, YOU! READ THE DOCS BEFORE YOU DO ANYTHING!
# https://spotizerr.rtfd.io

services:
  spotizerr:
    image: cooldockerizer93/spotizerr
    user: 99:100
    volumes:
      - /mnt/cache/appdata/spotizerr/data:/app/data
      - /mnt/user/Downloads/spotizerr:/app/downloads
      - /mnt/cache/appdata/spotizerr/logs:/app/logs
      # - /mnt/cache/appdata/spotizerr/.cache:/app/.cache
    ports:
      - 7171:7171
    container_name: spotizerr-app
    restart: unless-stopped
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.shell=bash
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    external: true
