services:
  syncthing:
    security_opt:
      - no-new-privileges:true
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=99
      - PGID=100
      - UMASK=000
    ports:
      - 8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - /mnt/user/:/data1:rw
      - /mnt/cache/Daten/:/data2:rw
      - /mnt/cache/appdata/syncthing:/config:rw
    networks:
      - backend
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:8384]
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syncthing-logo.png
      - net.unraid.docker.shell=bash
networks:
  backend:
    external: true
