services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=99
      - PGID=100
      - UMASK=000
    ports:
      - 8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - /mnt/user/:/data1:rw
      - /mnt/cache/Daten/:/data2:rw
      - /mnt/cache/appdata/syncthing:/config:rw
    networks:
      - backend
networks:
  backend:
    external: true
