services:
  palmr:
    security_opt:
      - no-new-privileges:true
    image: kyantech/palmr:latest
    container_name: palmr
    hostname: palmr
    networks:
      - backend
    environment:
      - PALMR_UID=99
      - PALMR_GID=100
      - DISABLE_FILESYSTEM_ENCRYPTION=true
      - ENCRYPTION_KEY=
      - DEFAULT_LANGUAGE=de-DE
      - SECURE_SITE=false
    ports:
      - 5487:5487/tcp
      - 3333:3333/tcp
    volumes:
      - /mnt/cache/appdata/palmr:/app/server
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:5487]
      - net.unraid.docker.icon=https://raw.githubusercontent.com/kyantech/Palmr/main/docs/assets/logo.png
networks:
  backend:
    external: true
