services:
  postgres:
    security_opt:
      - no-new-privileges:true
    image: postgres:18-alpine
    container_name: postgresql18
    hostname: postgresql18
    shm_size: 128mb
    healthcheck:
      # Pr√ºft alle 10s, ob die DB antwortet
      test:
        - CMD-SHELL
        - sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
      interval: 10s
      timeout: 5s
      retries: 5
      # ports:
      # - 5432:5432/tcp
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    secrets:
      - db_password
    volumes:
      - ./postgresql18:/var/lib/postgresql:rw
    networks:
      - backend
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/sgraaf/Unraid-Docker-Templates/main/postgresql18/icon.png
      - net.unraid.docker.shell=bash

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    ports:
      - 8086:8080/tcp
    environment:
      - HOST_CONTAINERNAME=adminer
      - ADMINER_DESIGN=dracula
      - ADMINER_PLUGINS=
    labels:
      - net.unraid.docker.managed=composeman
      - net.unraid.docker.webui=http://[IP]:[PORT:8080]
      - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/adminer.png
    networks:
      - backend
networks:
  backend:
    external: true

secrets:
  db_password:
    file: ./secrets/db_password.txt
